feat:impl renderPage base egg-view-swig and scrat-swig
scrat-team/egg-view-swig-pagelet pull request #1
Opened 2017-04-11 13:00 UTC by hubcarl

基于egg-view-swig插件扩展, 支持scrat pagelet 模式, context增加renderPage方法  第一版实现， 帮忙review 一下 哈哈 @atian25

2017-04-11 13:04 UTC, atian25 commented on app/extend/application.js
> +      this[ PAGELET_SWIG ] = engine(this);
不要空格

2017-04-11 13:04 UTC, atian25 commented on app/extend/context.js
> +  get swigPageletView() {
不打算依赖 egg-view-swig ?

2017-04-11 13:07 UTC, hubcarl commented on app/extend/application.js
> +      this[ PAGELET_SWIG ] = engine(this);
这个我的错，然后格式，我调整一下

2017-04-11 13:08 UTC, hubcarl commented on app/extend/context.js
> +  get swigPageletView() {
依赖了egg-view-swig，这个是进行扩展的

2017-04-12 01:46 UTC, atian25 requested changes

2017-04-12 01:46 UTC, atian25 commented on README.md
> +// $appname/config/plugin.js
`${app_rott}/config/plugin.js`

2017-04-12 01:46 UTC, atian25 commented on README.md
> +Set mapping in config
这句话不准确?

2017-04-12 01:46 UTC, atian25 commented on README.md
> +exports.swigPagelet = {
`${app_rott}/config/config.default.js`

2017-04-12 01:46 UTC, atian25 commented on README.md
> +  layout: 'layout/layout.tpl',
这几个都是默认值吧？注释掉还是怎么样，避免用户在应用里面又复制一次

2017-04-12 01:46 UTC, atian25 commented on README.md
> +  yield ctx.renderPage('home.tpl', { list });
感觉可以像上次说的那样，直接覆盖掉 render 方法。

2017-04-12 01:46 UTC, atian25 commented on app.js
> +  scratSwig.tagNames.forEach(tag => {
合并掉这个后，就不用这段逻辑了
https://github.com/scrat-team/scrat-swig/pull/14

2017-04-12 01:46 UTC, atian25 commented on app.js
> +  const root = app.config.view.root[0];
一般这个我们会赋值 app/views 和 app/view

这里可以考虑做下:
- 循环这个数组，过滤掉不存在的目录
- 取过滤后的第一个元素作为 root
- 如果过滤后的数组还是有多个，则发一个 warn

2017-04-12 01:46 UTC, atian25 commented on app.js
> +  const filters = app.loader.loadFile(path.join(app.baseDir, 'app/extend/filter.js')) || {};
这里只考虑了应用目录，可以支持下插件提供的 filter，参考 https://github.com/eggjs/egg-view-nunjucks/blob/master/lib/environment.js#L55 的写法

2017-04-12 01:46 UTC, atian25 commented on app/extend/context.js
> +  get swigPageletView() {
没必要加一个 swigPageletView 对象了，直接在 app/extend/context.js 里面加就好了吧

2017-04-12 01:46 UTC, atian25 commented on package.json
> +    "egg-view-swig": "^0.1.0",
这个不是 dependencies，最多只是作为 devDependencies 来测试

2017-04-12 01:46 UTC, atian25 commented on package.json
> +    "pagelet",
多了个

2017-04-12 01:46 UTC, atian25 commented on package.json
> +    "expect.js": "^0.3.1",
干掉

2017-04-12 01:46 UTC, atian25 commented on package.json
> +    "thunk-mocha": "^1.0.8",
干掉

2017-04-12 01:46 UTC, atian25 commented on package.json
> +  "homepage": "https://github.com/scrat-team/egg-view-pagelet-swig",
`pagelet-swig` 错了, 搜索下看其他地方还有没有

2017-04-12 01:46 UTC, atian25 commented on package.json
> +  "name": "egg-view-pagelet-swig",
pagelet-swig 错了

2017-04-12 03:37 UTC, hubcarl commented on README.md
> +  layout: 'layout/layout.tpl',
默认值

2017-04-12 03:39 UTC, hubcarl commented on README.md
> +  yield ctx.renderPage('home.tpl', { list });
建议不要覆盖，因为pagelet-swig 是直接 依赖的 view-swig的，这样render还是可以用的，不用基于layout也是可以的

2017-04-12 03:46 UTC, atian25 commented on README.md
> +  layout: 'layout/layout.tpl',
默认值的话，在这里就注释掉吧，提示用户可以这么改，但是默认不用配

2017-04-12 03:50 UTC, hubcarl commented on README.md
> +  layout: 'layout/layout.tpl',
我说明里面加一下default说明，同时注释掉

2017-04-12 03:53 UTC, atian25 commented on README.md
> +  yield ctx.renderPage('home.tpl', { list });
默认覆盖掉吧，既然用了这个插件，99% 的情况下就是走 pagelet 的模式。
如果需要原来的行为，他们可以：
```js
this.body = yield this.renderView(tpl, locals);
```

2017-04-12 04:01 UTC, atian25 commented on lib/view.js
> +  * renderPage(name, locals, options = {}) {
这个类不需要了，直接在 app/extend/context.js 里面扩展就好了。

```js
// app/extend/context.js
  // alias for renderPage
  render(...args) {
    return this.renderPage(...args);
  },

  renderPage(...args) {
    // beforeRender 代码直接拷贝进来, 不用独立函数了
    // setLocals 这个貌似不需要了, egg-view 里面做了
    // 其他代码
  },
```

2017-04-12 04:22 UTC, hubcarl commented on lib/view.js
> +  * renderPage(name, locals, options = {}) {
如果是自己扩展的方法， setLocals 需要自己处理， 如果是egg-view 的render和renderString 方法 setLocals会自动处理

2017-04-12 07:41 UTC, hubcarl commented
修改点： 
1.egg-view-pagelet-swig 改成 egg-view-swig-pagelet
2.renderPage 改成render 覆盖view-swig 的render
3.config.view.ext 改成 egg-view的defaultExtension

2017-04-12 07:53 UTC, atian25 commented on app.js
> +  const config = Object.assign({ swig: app.swig, map: swigPagelet.manifest }, swigPagelet);
这样写感觉不直观了，建议直接：

```js
const config = Object.assign({}, app.config.swigPagelet);
config.swig = app.swig;
config.map = config.manifest;
config.manifest = undefined;
```

2017-04-12 07:53 UTC, atian25 commented on app/extend/context.js
>      this.body = yield this.swigPageletView.renderPage(name, locals, options);
不用 swigPageletView 这个类了吧

2017-04-12 07:53 UTC, atian25 commented on config/config.default.js
>    config.swigPagelet = {
这里要写 jsdoc，参考其他几个库

2017-04-12 07:53 UTC, atian25 commented on lib/view.js
>      this.swigPagelet = this.app.config.swigPagelet;
this.config 好点

2017-04-12 07:53 UTC, atian25 commented on lib/view.js
> +    const normalName = name.replace(new RegExp(`${this.app.config.view.defaultExtension}$`, ''), '');
```
new RegExp(`\${this.app.config.view.defaultExtension}$`
```
需要多一个 `\`，因为第一个是 点

2017-04-12 08:05 UTC, hubcarl commented on lib/view.js
> +    const normalName = name.replace(new RegExp(`${this.app.config.view.defaultExtension}$`, ''), '');
对于变量是不需要的，还专门测试了一下，是没问题的

2017-04-12 08:12 UTC, hubcarl commented on app.js
> +  const config = Object.assign({ swig: app.swig, map: swigPagelet.manifest }, swigPagelet);
这个还好吧，逻辑比较简单

2017-04-12 08:15 UTC, hubcarl commented on lib/view.js
>      this.swigPagelet = this.app.config.swigPagelet;
已修改为this.config

2017-04-12 08:15 UTC, hubcarl commented on config/config.default.js
>    config.swigPagelet = {
swigPagelet 已加jsdoc

2017-04-12 08:19 UTC, hubcarl commented
第一次按照egg开源的规范写，细节问题挺多，多写几个，后面就会好很多。

2017-04-12 08:24 UTC, atian25 commented
https://github.com/scrat-team/egg-view-swig-pagelet/pull/1#discussion_r111050303
这个漏了，其他 +1

2017-04-12 08:34 UTC, hubcarl commented on app.js
> +  const root = app.config.view.root[0];
好，不过在pagelet里面已经没有了，要改egg-view-swig

2017-04-12 08:39 UTC, atian25 commented
哈哈，习惯就好，第一个 PR 肯定会很久

2017-04-12 08:40 UTC, merged

2017-04-12 09:31 UTC, atian25 commented
1.0.0